/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-08-03 20:46:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sist.com.dto.MovieBean;
import sist.com.dao.MovieDao;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("sist.com.dao.MovieDao");
    _jspx_imports_classes.add("sist.com.dto.MovieBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>인덱스</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("   <link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" >\r\n");
      out.write("   \r\n");
      out.write("   <!-- ICON -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Title -->\r\n");
      out.write("    <title>영화예매</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"img/core-img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Core Stylesheet -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    \r\n");
      out.write("   </head>   \r\n");
      out.write("    <style>\r\n");
      out.write("    th{\r\n");
      out.write("      text-align: center;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .movieList_wrapper{\r\n");
      out.write("      width:1200px; \r\n");
      out.write("      height: 500px;  \r\n");
      out.write("      margin: 50px; \r\n");
      out.write("      text-align: center;  \r\n");
      out.write("      margin: 0 auto;\r\n");
      out.write("   }\r\n");
      out.write("   .movieList{s\r\n");
      out.write("      overflow: hidden; \r\n");
      out.write("      position: relative; \r\n");
      out.write("      float: left; \r\n");
      out.write("      width: 230px; \r\n");
      out.write("      height: 350px; \r\n");
      out.write("      margin: 30px;\r\n");
      out.write("   }\r\n");
      out.write("    body \r\n");
      out.write("    {\r\n");
      out.write("       background-image:url(\"/orm/img/background.jpg\");\r\n");
      out.write("   }\r\n");
      out.write("    .booking{\r\n");
      out.write("\r\n");
      out.write("    \topacity: 0.8;\r\n");
      out.write("    }\r\n");
      out.write("    .header-area .delicious-main-menu .classy-navbar .classynav > ul > li > a \r\n");
      out.write("    {\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      padding: 12px 18px 11px;\r\n");
      out.write("      background-color: transparent;\r\n");
      out.write("      border-bottom: 3px solid transparent;\r\n");
      out.write("      line-height: 1;\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-weight: 600; \r\n");
      out.write("    }\r\n");
      out.write("    .classynav ul li ul li a {\r\n");
      out.write("    padding: 0 20px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    border-width: 10px;\r\n");
      out.write("    \r\n");
      out.write("\t}\r\n");
      out.write("    ul.dropdown\r\n");
      out.write("    {\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      padding: 12px 18px 11px;\r\n");
      out.write("      background-color: transparent;\r\n");
      out.write("      border-bottom: 3px solid transparent;\r\n");
      out.write("      line-height: 1;\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-weight: 600; \r\n");
      out.write("    } \r\n");
      out.write("    a, a:hover, a:focus \r\n");
      out.write("    {\r\n");
      out.write("     -webkit-transition-duration: 500ms;\r\n");
      out.write("     transition-duration: 500ms;\r\n");
      out.write("     text-decoration: none;\r\n");
      out.write("     outline: 0 solid transparent;\r\n");
      out.write("     color: #000000;\r\n");
      out.write("     font-weight: 600;\r\n");
      out.write("     font-size: 14px;\r\n");
      out.write("     color: white; \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .header-area .top-header-area .top-social-info a {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      color: #40ba37;\r\n");
      out.write("      font-size: 13px;\r\n");
      out.write("      margin-right: 30px; }\r\n");
      out.write("    ul{ width: 100%;}  \r\n");
      out.write("     \r\n");
      out.write("    li#boxOffice{\r\n");
      out.write("\r\n");
      out.write("       float: left; \r\n");
      out.write("       overflow: hidden; \r\n");
      out.write("       position: relative; \r\n");
      out.write("       width: 230px; \r\n");
      out.write("       height: 350px; \r\n");
      out.write("       margin: 30px;\r\n");
      out.write("    }\r\n");
      out.write("    button{\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    background-color: #40ba37;\r\n");
      out.write("    border-bottom: 3px solid #1c8314;\r\n");
      out.write("    }\r\n");
      out.write("    button#good{\r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("    div img#mainLogo{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("   top: 0; bottom: 0;\r\n");
      out.write("   left:0; right: 0;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* footer  */\r\n");
      out.write(".site-footer\r\n");
      out.write("{\r\n");
      out.write("  background-color:#26272b;\r\n");
      out.write("  padding:45px 0 20px;\r\n");
      out.write("  font-size:15px;\r\n");
      out.write("  line-height:24px;\r\n");
      out.write("  color:#737373;\r\n");
      out.write("}\r\n");
      out.write(".site-footer hr\r\n");
      out.write("{\r\n");
      out.write("  border-top-color:#bbb;\r\n");
      out.write("  opacity:0.5\r\n");
      out.write("}\r\n");
      out.write(".site-footer hr.small\r\n");
      out.write("{\r\n");
      out.write("  margin:20px 0\r\n");
      out.write("}\r\n");
      out.write(".site-footer h6\r\n");
      out.write("{\r\n");
      out.write("  color:#fff;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("  text-transform:uppercase;\r\n");
      out.write("  margin-top:5px;\r\n");
      out.write("  letter-spacing:2px\r\n");
      out.write("}\r\n");
      out.write(".site-footer a\r\n");
      out.write("{\r\n");
      out.write("  color:#737373;\r\n");
      out.write("}\r\n");
      out.write(".site-footer a:hover\r\n");
      out.write("{\r\n");
      out.write("  color:#3366cc;\r\n");
      out.write("  text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write(".footer-links\r\n");
      out.write("{\r\n");
      out.write("  padding-left:0;\r\n");
      out.write("  list-style:none\r\n");
      out.write("}\r\n");
      out.write(".footer-links li\r\n");
      out.write("{\r\n");
      out.write("  display:block\r\n");
      out.write("}\r\n");
      out.write(".footer-links a\r\n");
      out.write("{\r\n");
      out.write("  color:#737373\r\n");
      out.write("}\r\n");
      out.write(".footer-links a:active,.footer-links a:focus,.footer-links a:hover\r\n");
      out.write("{\r\n");
      out.write("  color:#3366cc;\r\n");
      out.write("  text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write(".footer-links.inline li\r\n");
      out.write("{\r\n");
      out.write("  display:inline-block\r\n");
      out.write("}\r\n");
      out.write(".site-footer .social-icons\r\n");
      out.write("{\r\n");
      out.write("  text-align:right\r\n");
      out.write("}\r\n");
      out.write(".site-footer .social-icons a\r\n");
      out.write("{\r\n");
      out.write("  width:40px;\r\n");
      out.write("  height:40px;\r\n");
      out.write("  line-height:40px;\r\n");
      out.write("  margin-left:6px;\r\n");
      out.write("  margin-right:0;\r\n");
      out.write("  border-radius:100%;\r\n");
      out.write("  background-color:#33353d\r\n");
      out.write("}\r\n");
      out.write(".copyright-text\r\n");
      out.write("{\r\n");
      out.write("  margin:0\r\n");
      out.write("}\r\n");
      out.write("@media (max-width:991px)\r\n");
      out.write("{\r\n");
      out.write("  .site-footer [class^=col-]\r\n");
      out.write("  {\r\n");
      out.write("    margin-bottom:30px\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("@media (max-width:767px)\r\n");
      out.write("{\r\n");
      out.write("  .site-footer\r\n");
      out.write("  {\r\n");
      out.write("    padding-bottom:0\r\n");
      out.write("  }\r\n");
      out.write("  .site-footer .copyright-text,.site-footer .social-icons\r\n");
      out.write("  {\r\n");
      out.write("    text-align:center\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(".social-icons\r\n");
      out.write("{\r\n");
      out.write("  padding-left:0;\r\n");
      out.write("  margin-bottom:0;\r\n");
      out.write("  list-style:none\r\n");
      out.write("}\r\n");
      out.write(".social-icons li\r\n");
      out.write("{\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  margin-bottom:4px\r\n");
      out.write("}\r\n");
      out.write(".social-icons li.title\r\n");
      out.write("{\r\n");
      out.write("  margin-right:15px;\r\n");
      out.write("  text-transform:uppercase;\r\n");
      out.write("  color:#96a2b2;\r\n");
      out.write("  font-weight:700;\r\n");
      out.write("  font-size:13px\r\n");
      out.write("}\r\n");
      out.write(".social-icons a{\r\n");
      out.write("  background-color:#eceeef;\r\n");
      out.write("  color:#818a91;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  line-height:44px;\r\n");
      out.write("  width:44px;\r\n");
      out.write("  height:44px;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("  margin-right:8px;\r\n");
      out.write("  border-radius:100%;\r\n");
      out.write("  -webkit-transition:all .2s linear;\r\n");
      out.write("  -o-transition:all .2s linear;\r\n");
      out.write("  transition:all .2s linear\r\n");
      out.write("}\r\n");
      out.write(".social-icons a:active,.social-icons a:focus,.social-icons a:hover\r\n");
      out.write("{\r\n");
      out.write("  color:#fff;\r\n");
      out.write("  background-color:#29aafe\r\n");
      out.write("}\r\n");
      out.write(".social-icons.size-sm a\r\n");
      out.write("{\r\n");
      out.write("  line-height:34px;\r\n");
      out.write("  height:34px;\r\n");
      out.write("  width:34px;\r\n");
      out.write("  font-size:14px\r\n");
      out.write("}\r\n");
      out.write(".social-icons a.facebook:hover\r\n");
      out.write("{\r\n");
      out.write("  background-color:#3b5998\r\n");
      out.write("}\r\n");
      out.write(".social-icons a.twitter:hover\r\n");
      out.write("{\r\n");
      out.write("  background-color:#00aced\r\n");
      out.write("}\r\n");
      out.write(".social-icons a.linkedin:hover\r\n");
      out.write("{\r\n");
      out.write("  background-color:#007bb6\r\n");
      out.write("}\r\n");
      out.write(".social-icons a.dribbble:hover\r\n");
      out.write("{\r\n");
      out.write("  background-color:#ea4c89\r\n");
      out.write("}\r\n");
      out.write("@media (max-width:767px)\r\n");
      out.write("{\r\n");
      out.write("  .social-icons li.title\r\n");
      out.write("  {\r\n");
      out.write("    display:block;\r\n");
      out.write("    margin-right:0;\r\n");
      out.write("    font-weight:600\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("div buttion#heart{\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write(" <script>\r\n");
      out.write("       $(function(){\r\n");
      out.write("          $(\"a#signup\").click(function(){\r\n");
      out.write("             //window.open(\"/orm/jsp/signup.jsp\",'left=300,top=100,width=400,height=300')\r\n");
      out.write("             document.location.href='/orm/jsp/signup.jsp';\r\n");
      out.write("          });\r\n");
      out.write("          $(\"a#signin\").click(function(){\r\n");
      out.write("             //window.open(\"/orm/jsp/signin.jsp\",'left=300,top=100,width=400,height=300')\r\n");
      out.write("             document.location.href='/orm/jsp/signin.jsp';\r\n");
      out.write("          });\r\n");
      out.write("          $(\"#btnSearch\").click(function(){\r\n");
      out.write("             var searchData=$(\"input#movieSearch\").val();\r\n");
      out.write("             if(searchData.length==0){\r\n");
      out.write("               alert('영화명을 입력해 주세요');\r\n");
      out.write("               $(\"input#movieSearch\").val('');\r\n");
      out.write("               $(\"input#movieSearch\").focus();\r\n");
      out.write("             }else{\r\n");
      out.write("                alert(searchData);\r\n");
      out.write("                $(\"form#searchFrm\").submit();\r\n");
      out.write("             }\r\n");
      out.write("            \r\n");
      out.write("          });\r\n");
      out.write("\r\n");
      out.write("          if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"!=null && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length>0){\r\n");
      out.write("             if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length>0 && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"!='admin'){\r\n");
      out.write("            $(\"a#mypage\").show();\r\n");
      out.write("            $(\"a#logOut\").show();\r\n");
      out.write("            $(\"a#sign\").hide();\r\n");
      out.write("            $(\"a#signup\").hide();\r\n");
      out.write("            $(\"a#signup\").hide();\r\n");
      out.write("            $(\"a#adminpage\").hide();}\r\n");
      out.write("             if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length>0 && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"=='admin'){ \r\n");
      out.write("                $(\"a#mypage\").hide();\r\n");
      out.write("                $(\"a#logOut\").show();\r\n");
      out.write("                $(\"a#sign\").hide();\r\n");
      out.write("                $(\"a#signup\").hide();\r\n");
      out.write("                $(\"a#signup\").hide();\r\n");
      out.write("                $(\"a#adminpage\").show();}\r\n");
      out.write("             }\r\n");
      out.write("            else{\r\n");
      out.write("               $(\"a#adminpage\").hide();\r\n");
      out.write("               $(\"a#mypage\").hide();\r\n");
      out.write("               $(\"a#logOut\").hide();\r\n");
      out.write("               $(\"a#sign\").show();\r\n");
      out.write("            \r\n");
      out.write("            }  \r\n");
      out.write("            \r\n");
      out.write("            $.ajax({\r\n");
      out.write("               url:'/orm/mainMovieList.do',\r\n");
      out.write("               datatype:'text',\r\n");
      out.write("               success:function(v){\r\n");
      out.write("                     var listAppend=\"\"; \r\n");
      out.write("                  $(v).each(function(index,dom){\r\n");
      out.write("                      //좋아요버튼은 class=\"like\" 예매버튼은 class=\"booking\" \r\n");
      out.write("                     listAppend+=\"<div class='movieList' >\";\r\n");
      out.write("                     listAppend+=\"<a href='MovieInfo.do?no=\"+dom.movie_no+\"'><img alt='' src='/orm/img/poster/\"+dom.poster_img+\"'></img></a>\";\r\n");
      out.write("                     listAppend+=\"<div id='good' ><button id='heart'style='background-color:black;border-bottom: 2px'><i class='far fa-heart' style='font-size:24px;color:white;'></i></button>\";\r\n");
      out.write("                     listAppend+=\"<a href='#'style='background-color:black; ><button class='booking' >예매</button></a></div>\";\r\n");
      out.write("                     listAppend+=\"</div> \";  \r\n");
      out.write("                  });\r\n");
      out.write("                   $(\"div.movieList_wrapper\").append(listAppend); \r\n");
      out.write("               },\r\n");
      out.write("               eroor:function(){\r\n");
      out.write("                  alert('error');\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("       });\r\n");
      out.write("  \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Preloader -->\r\n");
      out.write("    <div id=\"preloader\">\r\n");
      out.write("        <i class=\"circle-preloader\"></i>\r\n");
      out.write("        <img src=\"img/core-img/salad.png\" alt=\"\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Search Wrapper -->\r\n");
      out.write("    <div class=\"search-wrapper\">\r\n");
      out.write("        <!-- Close Btn -->\r\n");
      out.write("        <div class=\"close-btn\"><i class=\"fa fa-times\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <form action=\"#\" method=\"post\">\r\n");
      out.write("                        <input type=\"search\" name=\"search\" placeholder=\"Type any keywords...\">\r\n");
      out.write("                        <button type=\"submit\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Header Area Start ##### -->\r\n");
      out.write("    <header class=\"header-area\">\r\n");
      out.write("\r\n");
      out.write("       <!--  Top Header Area -->\r\n");
      out.write("        <div class=\"top-header-area\">\r\n");
      out.write("            <div class=\"container h-100\">\r\n");
      out.write("                <div class=\"row h-100 align-items-center justify-content-between\">\r\n");
      out.write("                <div><a href=\"index.jsp\"><img id=\"mainLogo\" src=\"img/mainLogo.png\" alt=\"\" style=\"padding-bottom: 100px;\"></a></div>\r\n");
      out.write("                <!--     Breaking News -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6\">\r\n");
      out.write("                    \t\r\n");
      out.write("                        <div class=\"breaking-news\">\r\n");
      out.write("                            <div id=\"breakingNewsTicker\" class=\"ticker\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\">Hello World!</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Welcome to MovieBox</a></li>\r\n");
      out.write("                                   <!--  <li><a href=\"#\">Have a goo time!</a></li> -->\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write(" \r\n");
      out.write("          \r\n");
      out.write("                    <!-- Top Social Info -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6\">\r\n");
      out.write("                        <div class=\"top-social-info text-right\">\r\n");
      out.write("                          <!--   <a href=\"#\"><i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></a> -->\r\n");
      out.write("                            <a href=\"signup.do\" id=\"signup\" >회원가입</a><!--로그인시 hidden 처리되게  -->\r\n");
      out.write("                            <a href=\"signin.do\" id=\"sign\" >로그인</a><!--로그인시 '로그아웃'으로 바뀌게 하기  -->\r\n");
      out.write("                            <a href=\"logOut.do\" id=\"logOut\" >로그아웃</a><!--로그인시 '로그아웃'으로 바뀌게 하기  -->\r\n");
      out.write("                            <a href=\"boardList.do\">고객센터</a>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Navbar Area -->\r\n");
      out.write("        <div class=\"delicious-main-menu\">\r\n");
      out.write("            <div class=\"classy-nav-container breakpoint-off\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    \r\n");
      out.write("                        \r\n");
      out.write("                    <!-- Menu -->\r\n");
      out.write("                    <nav class=\"classy-navbar justify-content-between\" id=\"deliciousNav\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- Navbar Toggler -->\r\n");
      out.write("                        <div class=\"classy-navbar-toggler\">\r\n");
      out.write("                            <span class=\"navbarToggler\"><span></span><span></span><span></span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Menu -->\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"classy-menu\">\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                            <!-- close btn -->\r\n");
      out.write("                            <div class=\"classycloseIcon\">\r\n");
      out.write("                                <div class=\"cross-wrap\"><span class=\"top\"></span><span class=\"bottom\"></span></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                     \r\n");
      out.write("                            <!-- Nav Start -->\r\n");
      out.write("                            <div class=\"classynav\" style=\"position: absolute;\">\r\n");
      out.write("                                <ul \"class=\"nav-item active\">\r\n");
      out.write("                                    <!-- <li class=\"active\"><a href=\"index.jsp\">Home</a></li> -->\r\n");
      out.write("                                    <li><a href=\"#\" style=\"padding-right: 68px; padding-left: 68px;\">영  화</a>\r\n");
      out.write("                                        <ul class=\"dropdown\">\r\n");
      out.write("                                            <li><a href=\"index.jsp\">홈</a></li>\r\n");
      out.write("                                            <li><a href=\"about.html\">박스오피스</a></li>\r\n");
      out.write("                                            <li><a href=\"blog-post.html\">상영예정작</a></li>\r\n");
      out.write("                                            <li><a href=\"receipe-post.html\">무비파인더</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"#\" style=\"padding-right: 68px; padding-left: 68px;\">예  매</a>\r\n");
      out.write("                                      <ul class=\"dropdown\">\r\n");
      out.write("                                            <li><a href=\"/orm/bookingList.do\">빠른예매</a></li>\r\n");
      out.write("                                           <!--  <li><a href=\"#\">상영시간표</a></li> -->\r\n");
      out.write("                                      </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"#\" style=\"padding-right: 68px; padding-left: 68px;\">극  장</a>\r\n");
      out.write("                                      <ul class=\"dropdown\">\r\n");
      out.write("                                            <li><a href=\"index.html\">전체극장</a></li>\r\n");
      out.write("                          \r\n");
      out.write("                                      </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"receipe-post.html\" style=\"padding-right:68px; padding-left: 68px;\">이벤트</a>\r\n");
      out.write("                                     <ul class=\"dropdown\">\r\n");
      out.write("                                            <li><a href=\"index.html\">진행중 이벤트</a></li>\r\n");
      out.write("                                            <li><a href=\"about.html\">지난 이벤트</a></li>\r\n");
      out.write("                                            <li><a href=\"about.html\">당첨자 발표</a></li>\r\n");
      out.write("                                      </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <!-- <li><a href=\"receipe-post.html\" style=\"padding-right: 68px; padding-left: 68px;\">스토어</a></li> -->\r\n");
      out.write("                                    <li><a href=\"contact.html\" style=\"padding-right: 68px; padding-left: 68px;\">혜택</a>\r\n");
      out.write("                                       <ul class=\"dropdown\">\r\n");
      out.write("                                            <li><a href=\"index.html\">메가 박스</a></li>\r\n");
      out.write("                                            <li><a href=\"about.html\">제휴/할인</a></li>\r\n");
      out.write("                                            <li><a href=\"about.html\">당첨자 발표</a></li>\r\n");
      out.write("                                      </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a id=\"mypage\" href=\"MyPage.do\" style=\"padding-right: 68px; padding-left: 68px;\">마이페이지</a></li>\r\n");
      out.write("                                    <li><a id=\"adminpage\" href=\"#\" style=\"padding-right: 68px; padding-left: 68px;\">관리자페이지</a>\r\n");
      out.write("                                       <ul class=\"dropdown\">\r\n");
      out.write("                                           <li><a href=\"/orm/uploadMovie.jsp\">영화입력</a></li>\r\n");
      out.write("                                           <li><a href=\"#\">게시글 관리</a></li>\r\n");
      out.write("                                           <li><a href=\"#\">Q&A게시판 등록</a></li>\r\n");
      out.write("                                           <li><a href=\"#\">Q&A게시판 수정</a></li>\r\n");
      out.write("                                           \r\n");
      out.write("                                     </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    \r\n");
      out.write("                                </ul>\r\n");
      out.write("               \r\n");
      out.write("                                <!-- Newsletter Form -->\r\n");
      out.write("                            <!--     <div class=\"search-btn\">\r\n");
      out.write("                                    <i class=\"fa fa-search\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                </div> -->\r\n");
      out.write("                            <!-- <div class=\"link-area\">\r\n");
      out.write("                             <a href=\"#\" class=\"header-icon-join\" title=\"마이 페이지\" style=\"margin-right: 10px;\">마이페이지</a>\r\n");
      out.write("                             <a href=\"#\" class=\"header-icon-ticket\" title=\"상영시간표\">상영시간표</a>\r\n");
      out.write("                            </div> -->\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Nav End -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div width: 100%; height: 600px\">\r\n");
      out.write("       <!-- <div class=\"contentArea\">\r\n");
      out.write("         <div class=\"tab_box\">\r\n");
      out.write("            <button type=\"button\" class=\"tab_box_btn\" sort=\"boxoRankList\" style=\"width: 100px; height: 30px;\">박스오피스</button>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div> -->\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("        <!--영화 메인 포스터  시작-->\r\n");
      out.write("       \r\n");
      out.write("          <!--영화 메인 포스터  시작-->\r\n");
      out.write("        <p class=\"\">\r\n");
      out.write("           <div  class=\"movieList_wrapper\" >\r\n");
      out.write("        </p>\r\n");
      out.write("        \r\n");
      out.write("      <!--영화 메인 포스터 끝  -->\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("   </div>\r\n");
      out.write("      <!--검색 바 시작-->\r\n");
      out.write("      <form id=\"searchFrm\" action=\"/orm/movieSearch.jsp\" method=\"post\">\r\n");
      out.write("         <div class=\"search-link\">\r\n");
      out.write("            <div class=\"cell\">\r\n");
      out.write("               <div class=\"search\">\r\n");
      out.write("               <input type=\"text\" placeholder=\"영화명을 입력해 주세요\" title=\"영화 검색\" class=\"input-text\" id=\"searchData\" name=\"searchData\">\r\n");
      out.write("               <button type=\"button\" class=\"btn\" id=\"btnSearch\"><i class=\"iconset ico-search-w\"></i> 검색</button>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("      \r\n");
      out.write("               <div class=\"cell\"><a href=\"#\" title=\"상영시간표 보기\"><i class=\"fas fa-calendar-alt\" style=\"font-size:24px;color:white;\"></i> 상영시간표</a></div>\r\n");
      out.write("               <div class=\"cell\"><a href=\"#\" title=\"박스오피스 보기\"><i class=\"fas fa-film\" style=\"font-size:24px;color:white;\"></i> 박스오피스</a></div>\r\n");
      out.write("               <div class=\"cell\"><a href=\"#\" title=\"빠른예매 보기\"><i class=\"fas fa-ticket-alt\" style=\"font-size:24px;color:white;\"></i> 빠른예매</a></div>\r\n");
      out.write("         </div>\r\n");
      out.write("         </form>\r\n");
      out.write("      <!--검색바 끝 -->\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Footer Area Start ##### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### All Javascript Files ##### -->\r\n");
      out.write("    <!-- jQuery-2.2.4 js -->\r\n");
      out.write("    <script src=\"js/jquery/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("    <!-- Popper js -->\r\n");
      out.write("    <script src=\"js/bootstrap/popper.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap js -->\r\n");
      out.write("    <script src=\"js/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- All Plugins js -->\r\n");
      out.write("    <script src=\"js/plugins/plugins.js\"></script>\r\n");
      out.write("    <!-- Active js -->\r\n");
      out.write("    <script src=\"js/active.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Site footer -->\r\n");
      out.write("    <footer class=\"site-footer\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-xs-6 col-md-3\">\r\n");
      out.write("            <h6>Categories</h6>\r\n");
      out.write("            <ul class=\"footer-links\">\r\n");
      out.write("              <li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("              <li><a href=\"#\">자주묻는질문</a></li>\r\n");
      out.write("              <li><a href=\"#\">1:1 문의</a></li>\r\n");
      out.write("              <li><a href=\"#\">단체/대관문의</a></li>\r\n");
      out.write("              <li><a href=\"#\">분실물 문의/접수</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-xs-6 col-md-3\">\r\n");
      out.write("            <h6>Quick Links</h6>\r\n");
      out.write("            <ul class=\"footer-links\">\r\n");
      out.write("              <li><a href=\"#\">회사소개</a></li>\r\n");
      out.write("              <li><a href=\"#\">인재채용</a></li>\r\n");
      out.write("              <li><a href=\"#\">사회공헌</a></li>\r\n");
      out.write("              <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("              <li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("              <li><a href=\"#\">제휴/광고/부대사업문의</a></li>\r\n");
      out.write("              <li><a href=\"#\">윤리경영</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"col-sm-12 col-md-6\">\r\n");
      out.write("            <h6>About</h6>\r\n");
      out.write("            <p class=\"text-justify\">서울특별시 성동구 왕십리로 50, 6층(성수동 1가, 메가박스스퀘어) ARS 1544-0070 \r\n");
      out.write("                              대표자명 김진선 · 개인정보보호책임자 조상연 · 사업자등록번호 211-86-59478 · 통신판매업신고번호 제 833호</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        <hr>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-8 col-sm-6 col-xs-12\">\r\n");
      out.write("            <p class=\"copyright-text\">COPYRIGHT &copy; MegaboxJoongAng, Inc. All rights reserved \r\n");
      out.write("         <a href=\"#\">Scanfcode</a>.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("            <ul class=\"social-icons\">\r\n");
      out.write("              <li><a class=\"facebook\" href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("              <li><a class=\"twitter\" href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("              <li><a class=\"dribbble\" href=\"#\"><i class=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("              <li><a class=\"linkedin\" href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>   \r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
