/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-08-07 08:08:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sist.com.dto.MovieBean;
import sist.com.dao.MovieDao;
import java.util.List;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("sist.com.dao.MovieDao");
    _jspx_imports_classes.add("sist.com.dto.MovieBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>인덱스</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <script src=\"https://ajax.\tgoogleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("  <!-- <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("   ICON\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\"/>\r\n");
      out.write(" -->\r\n");
      out.write("   \r\n");
      out.write("    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Title -->\r\n");
      out.write("    <title>영화예매</title>\r\n");
      out.write("<!-- \r\n");
      out.write("    Favicon\r\n");
      out.write(" -->\r\n");
      out.write("    <!-- <link rel=\"icon\" href=\"img/core-img/favicon.ico\"> -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- Core Stylesheet -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("   </head>   \r\n");
      out.write("    <style>\r\n");
      out.write("    th{\r\n");
      out.write("      text-align: center;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .movieList_wrapper{\r\n");
      out.write("      width:1200px; \r\n");
      out.write("      height: 500px;  \r\n");
      out.write("      margin: 50px; \r\n");
      out.write("      text-align: center;  \r\n");
      out.write("      margin: 0 auto;\r\n");
      out.write("   }\r\n");
      out.write("   .movieList{\r\n");
      out.write("      overflow: hidden; \r\n");
      out.write("      position: relative; \r\n");
      out.write("      float: left; \r\n");
      out.write("      width: 230px; \r\n");
      out.write("      height: 350px; \r\n");
      out.write("      margin: 30px;\r\n");
      out.write("   }\r\n");
      out.write("    body \r\n");
      out.write("    {\r\n");
      out.write("       background-image:url(\"/orm/img/background.jpg\");\r\n");
      out.write("   }\r\n");
      out.write("    .booking{\r\n");
      out.write("\r\n");
      out.write("    \topacity: 0.8;\r\n");
      out.write("    }\r\n");
      out.write("      \r\n");
      out.write("    li#boxOffice{\r\n");
      out.write("\r\n");
      out.write("       float: left; \r\n");
      out.write("       overflow: hidden; \r\n");
      out.write("       position: relative; \r\n");
      out.write("       width: 230px; \r\n");
      out.write("       height: 350px; \r\n");
      out.write("       margin: 30px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    button{\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    background-color: #40ba37;\r\n");
      out.write("    border-bottom: 3px solid #1c8314;\r\n");
      out.write("    }\r\n");
      out.write("    /* button#good{\r\n");
      out.write("    \t\r\n");
      out.write("    } */\r\n");
      out.write("    div img#mainLogo{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("   top: 0; bottom: 0;\r\n");
      out.write("   left:0; right: 0;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write(" <script>\r\n");
      out.write("       $(function(){\r\n");
      out.write("         /*  $(\"a#signup\").click(function(){\r\n");
      out.write("             //window.open(\"/orm/jsp/signup.jsp\",'left=300,top=100,width=400,height=300')\r\n");
      out.write("             document.location.href='/orm/jsp/signup.jsp';\r\n");
      out.write("          });\r\n");
      out.write("          $(\"a#signin\").click(function(){\r\n");
      out.write("             //window.open(\"/orm/jsp/signin.jsp\",'left=300,top=100,width=400,height=300')\r\n");
      out.write("             document.location.href='/orm/jsp/signin.jsp';\r\n");
      out.write("          });\r\n");
      out.write("          $(\"#btnSearch\").click(function(){\r\n");
      out.write("             var searchData=$(\"input#movieSearch\").val();\r\n");
      out.write("             if(searchData.length==0){\r\n");
      out.write("               alert('영화명을 입력해 주세요');\r\n");
      out.write("               $(\"input#movieSearch\").val('');\r\n");
      out.write("               $(\"input#movieSearch\").focus();\r\n");
      out.write("             }else{\r\n");
      out.write("                alert(searchData);\r\n");
      out.write("                $(\"form#searchFrm\").submit();\r\n");
      out.write("             }\r\n");
      out.write("            \r\n");
      out.write("          });\r\n");
      out.write("\r\n");
      out.write("          if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"!=null && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length>0){\r\n");
      out.write("             if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length>0 && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"!='admin'){\r\n");
      out.write("            $(\"a#mypage\").show();\r\n");
      out.write("            $(\"a#logOut\").show();\r\n");
      out.write("            $(\"a#sign\").hide();\r\n");
      out.write("            $(\"a#signup\").hide();\r\n");
      out.write("            $(\"a#signup\").hide();\r\n");
      out.write("            $(\"a#adminpage\").hide();}\r\n");
      out.write("             if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length>0 && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"=='admin'){ \r\n");
      out.write("                $(\"a#mypage\").hide();\r\n");
      out.write("                $(\"a#logOut\").show();\r\n");
      out.write("                $(\"a#sign\").hide();\r\n");
      out.write("                $(\"a#signup\").hide();\r\n");
      out.write("                $(\"a#signup\").hide();\r\n");
      out.write("                $(\"a#adminpage\").show();}\r\n");
      out.write("             }\r\n");
      out.write("            else{\r\n");
      out.write("               $(\"a#adminpage\").hide();\r\n");
      out.write("               $(\"a#mypage\").hide();\r\n");
      out.write("               $(\"a#logOut\").hide();\r\n");
      out.write("               $(\"a#sign\").show();\r\n");
      out.write("            \r\n");
      out.write("            }   */\r\n");
      out.write("            \r\n");
      out.write("            $.ajax({\r\n");
      out.write("               url:'/orm/mainMovieList.do',\r\n");
      out.write("               datatype:'text',\r\n");
      out.write("               success:function(v){\r\n");
      out.write("                     var listAppend=\"\"; \r\n");
      out.write("                  $(v).each(function(index,dom){\r\n");
      out.write("                      //좋아요버튼은 class=\"like\" 예매버튼은 class=\"booking\" \r\n");
      out.write("                     listAppend+=\"<div class='movieList' >\";\r\n");
      out.write("                     listAppend+=\"<a href='MovieInfo.do?no=\"+dom.movie_no+\"'><img alt='' src='/orm/img/poster/\"+dom.poster_img+\"'></img></a>\";\r\n");
      out.write("                     /* listAppend+=\"<div id='good' ><button id='heart'style='background-color:black;border-bottom: 2px'><i class='far fa-heart' style='font-size:24px;color:white;'></i></button>\"; */\r\n");
      out.write("                     /* listAppend+=\"<a href='#'style='background-color:black; ><button class='booking' >예매</button></a></div>\"; */\r\n");
      out.write("                     listAppend+=\"</div> \";  \r\n");
      out.write("                  });\r\n");
      out.write("                   $(\"div.movieList_wrapper\").append(listAppend); \r\n");
      out.write("               },\r\n");
      out.write("               eroor:function(){\r\n");
      out.write("                  alert('error');\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("       });\r\n");
      out.write("  \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Header Area Start ##### -->\r\n");
      out.write("\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/pages_css/header2.jsp", out, false);
      out.write("\r\n");
      out.write("            \r\n");
      out.write("     \r\n");
      out.write("<!-- ##### Header Area End ##### -->\r\n");
      out.write("      <!--영화 메인 포스터  시작-->\r\n");
      out.write("    \t<p class=\"\">\r\n");
      out.write("        \t<div  class=\"movieList_wrapper\" >\r\n");
      out.write("    \t</p>\r\n");
      out.write("      <!--영화 메인 포스터 끝  -->\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Footer Area Start ##### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### All Javascript Files ##### -->\r\n");
      out.write("    <!-- jQuery-2.2.4 js -->\r\n");
      out.write("    <script src=\"./js/jquery/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("    <!-- Popper js -->\r\n");
      out.write("    <script src=\"./js/bootstrap/popper.min.js\"></script> \r\n");
      out.write("    <!-- Bootstrap js -->\r\n");
      out.write("    <!-- <script src=\"js/bootstrap/bootstrap.min.js\"></script> -->\r\n");
      out.write("    <!-- All Plugins js -->\r\n");
      out.write("    <script src=\"./js/plugins/plugins.js\"></script>\r\n");
      out.write("    <!-- Active js -->\r\n");
      out.write("    <script src=\"./js/active.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Site footer Start -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/pages_css/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- Site footer End-->\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
