/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-08-01 20:32:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sist.com.dao.MemberDao;
import sist.com.dto.MemberBean;

public final class MyPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/Project/MovieBox_final/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1590322652987L));
    _jspx_dependants.put("jar:file:/D:/Project/MovieBox_final/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sist.com.dto.MemberBean");
    _jspx_imports_classes.add("sist.com.dao.MemberDao");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script> -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.0.min.js\"></script>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=7\" />\r\n");
      out.write("\t<meta http-equiv=\"imagetoolbar\" content=\"no\" />\r\n");
      out.write("\t<link href=\"/orm/css/contents.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"style.css\"><style>\r\n");
      out.write("\r\n");
      out.write("tbody#myPage tr{\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("a:hover{\r\n");
      out.write("background-color: #40ba37;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#homeBody h2, b\r\n");
      out.write("{\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a#info, a#seat{\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write(".nav-tabs>li>a {\r\n");
      out.write("    margin-right: 2px;\r\n");
      out.write("    line-height: 1.42857143;\r\n");
      out.write("    border: 1px solid transparent;\r\n");
      out.write("    border-radius: 4px 4px 0 0;\r\n");
      out.write("    color: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body \r\n");
      out.write("    {\r\n");
      out.write("       background-image:url(\"/orm/img/background.jpg\");\r\n");
      out.write("\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("tr th {\r\n");
      out.write("   text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   color:#FFFFFF;\r\n");
      out.write("}\r\n");
      out.write(".bbsList tbody td{\r\n");
      out.write("\tborder-right: 1px solid #ddd\r\n");
      out.write("}\r\n");
      out.write("span{\r\n");
      out.write("\tcolor:#FFFFFF;\r\n");
      out.write("} \r\n");
      out.write(".bbsList thead th {\r\n");
      out.write("\tborder-right: 1px solid #ddd\r\n");
      out.write("} \r\n");
      out.write("</style>\r\n");
      out.write("    <title>영화예매</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"img/core-img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Core Stylesheet -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write(" <script>\r\n");
      out.write(" \tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"==null && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length<0){\r\n");
      out.write("\t window.location=\"/orm/index.jsp\"\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write(" \t\r\n");
      out.write(" \tfunction memberinfo(){\r\n");
      out.write(" \t\t$.ajax({\r\n");
      out.write("\t\t\turl:'/orm/memberInfo.do',\r\n");
      out.write("\t\t\ttype:'post',\r\n");
      out.write("\t\t\tdataType:'json',\r\n");
      out.write("\t\t\tdata:{id:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'},\r\n");
      out.write("\t\t\tsuccess:function(v){\r\n");
      out.write("\t\t\t\t$(\"#myPage\").append(\"<tr><td>이름:\"+v.name+\"</td></tr>\");\r\n");
      out.write("\t\t\t\t$(\"#myPage\").append(\"<tr><td>생년원일:\"+v.birth+\"</td></tr>\");\r\n");
      out.write("\t\t\t\t$(\"#myPage\").append(\"<tr><td>Tel:\"+v.tel+\"</td></tr>\");\r\n");
      out.write("\t\t\t\t$(\"#myPage\").append(\"<tr><td>E-mail:\"+v.email+\"</td></tr>\");\r\n");
      out.write("\t\t\t},error:function(){\r\n");
      out.write("\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write(" \t}\r\n");
      out.write(" \tfunction mySeatList(){\r\n");
      out.write(" \t\t$.ajax({\r\n");
      out.write("\t\t\turl:'/orm/mySeatList.do',\r\n");
      out.write("\t\t\ttype:'post',\r\n");
      out.write("\t\t\tdataType:'json',\r\n");
      out.write("\t\t\tdata:{id:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'},\r\n");
      out.write("\t\t\tsuccess:function(v){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t $(v).each(function(i,d){\r\n");
      out.write("\t\t\t\t\tconsole.log(d.booking_no)\r\n");
      out.write("\t\t\t\t\t$(\"#seat\").append(\"<tr>\");\r\n");
      out.write("\t\t\t\t\t$(\"#seat\").append(\"<td>\"+d.booking_no+\"</td>\");\r\n");
      out.write("\t\t\t\t\t$(\"#seat\").append(\"<td>\"+d.movie_regdate+\"</td>\");\r\n");
      out.write("\t\t\t\t\t$(\"#seat\").append(\"<td>\"+d.movie_name+\"</td>\");\r\n");
      out.write("\t\t\t\t\t$(\"#seat\").append(\"<td>\"+d.movie_loc+\"</td>\");\r\n");
      out.write("\t\t\t\t\t$(\"#seat\").append(\"<td>\"+d.movie_screen+\"</td>\");\r\n");
      out.write("\t\t\t\t\t$(\"#seat\").append(\"<td>\"+d.movie_time+\"</td>\");\r\n");
      out.write("\t\t\t\t\t$(\"#seat\").append(\"<td>\"+d.seat+\"</td>\");\r\n");
      out.write("\t\t\t\t\t$(\"#seat\").append(\"<td>\"+d.booking_amount+\"</td>\");\r\n");
      out.write("\t\t\t\t\t$(\"#seat\").append(\"<td>\"+d.booking_charge+\"원</td>\");\r\n");
      out.write("\t\t\t\t\t/* $(\"#seat\").append(\"<td><a href='SeatDelete.do?booking_no=\"+d.booking_no+\"'>\"+\"<button>예매취소</button></a></td>\"); */\r\n");
      out.write("\t\t\t\t\t$(\"#seat\").append(\"</tr>\");\r\n");
      out.write("\t\t\t\t\t/*\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("  */\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t},error:function(){\r\n");
      out.write("\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write(" \t}\r\n");
      out.write("\r\n");
      out.write("    \t$(function(){\r\n");
      out.write("    \t\tmemberinfo();\r\n");
      out.write("    \t\tmySeatList();\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t});\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Preloader -->\r\n");
      out.write("    <div id=\"preloader\">\r\n");
      out.write("        <i class=\"circle-preloader\"></i>\r\n");
      out.write("        <img src=\"img/core-img/salad.png\" alt=\"\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Search Wrapper -->\r\n");
      out.write("    <div class=\"search-wrapper\">\r\n");
      out.write("        <!-- Close Btn -->\r\n");
      out.write("        <div class=\"close-btn\"><i class=\"fa fa-times\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <form action=\"#\" method=\"post\">\r\n");
      out.write("                        <input type=\"search\" name=\"search\" placeholder=\"Type any keywords...\">\r\n");
      out.write("                        <button type=\"submit\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Header Area Start ##### -->\r\n");
      out.write("    <header class=\"header-area\">\r\n");
      out.write("\r\n");
      out.write("       <!--  Top Header Area -->\r\n");
      out.write("        <div class=\"top-header-area\">\r\n");
      out.write("            <div class=\"container h-100\">\r\n");
      out.write("                <div class=\"row h-100 align-items-center justify-content-between\">\r\n");
      out.write("                <!--     Breaking News -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6\">\r\n");
      out.write("                        <div class=\"breaking-news\">\r\n");
      out.write("                            <div id=\"breakingNewsTicker\" class=\"ticker\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\">Hello World!</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Welcome to MovieBox!!</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write(" \r\n");
      out.write("          \r\n");
      out.write("                    <!-- Top Social Info -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6\">\r\n");
      out.write("                        <div class=\"top-social-info text-right\">\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                            <a href=\"logOut.do\" id=\"signout\">로그아웃</a><!--로그인시 '로그아웃'으로 바뀌게 하기  -->\r\n");
      out.write("                            <a href=\"boardList.do\">고객센터</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Navbar Area -->\r\n");
      out.write("        <div class=\"delicious-main-menu\">\r\n");
      out.write("            <div class=\"classy-nav-container breakpoint-off\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <!-- Menu -->\r\n");
      out.write("                    <nav class=\"classy-navbar justify-content-between\" id=\"deliciousNav\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Logo -->\r\n");
      out.write("                        <a class=\"nav-brand\" href=\"#\"><img src=\"img/core-img/logo.png\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Navbar Toggler -->\r\n");
      out.write("                        <div class=\"classy-navbar-toggler\">\r\n");
      out.write("                            <span class=\"navbarToggler\"><span></span><span></span><span></span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Menu -->\r\n");
      out.write("                        <div class=\"classy-menu\">\r\n");
      out.write("\r\n");
      out.write("                            <!-- close btn -->\r\n");
      out.write("                            <div class=\"classycloseIcon\">\r\n");
      out.write("                                <div class=\"cross-wrap\"><span class=\"top\"></span><span class=\"bottom\"></span></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Nav Start -->\r\n");
      out.write("                          <div class=\"classynav\"> \r\n");
      out.write("                              <ul>\r\n");
      out.write("                                  <li><a href=\"index.jsp\" style=\"color: white;\">Home</a></li>\r\n");
      out.write("                                  <li><a style=\"color: white;\" href=\"#\">영화</a>\r\n");
      out.write("                                      <ul class=\"dropdown\">\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"index.jsp?id=\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">홈</a></li>\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"about.html\">박스오피스</a></li>\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"blog-post.html\">상영예정작</a></li>\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"receipe-post.html\">무비파인더</a></li>\r\n");
      out.write("                                      </ul>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                                  <li><a href=\"#\" style=\"color: white;\">예매</a>\r\n");
      out.write("                                    <ul class=\"dropdown\">\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"/orm/bookingList.do\">빠른예매</a></li>\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"about.html\">상영시간표</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                                  <li><a href=\"#\" style=\"color: white;\">극장</a>\r\n");
      out.write("                                    <ul class=\"dropdown\">\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"index.html\">전체극장</a></li>\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"about.html\">특별관</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                                  <li><a style=\"color: white;\" href=\"receipe-post.html\">이벤트</a>\r\n");
      out.write("                                   <ul class=\"dropdown\">\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"index.html\">진행중 이벤트</a></li>\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"about.html\">지난 이벤트</a></li>\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"about.html\">당첨자 발표</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                                  <li><a style=\"color: white;\" href=\"receipe-post.html\">스토어</a></li>\r\n");
      out.write("                                  <li><a style=\"color: white;\" href=\"contact.html\">혜택</a>\r\n");
      out.write("                                     <ul class=\"dropdown\">\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"index.html\">메가 박스</a></li>\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"about.html\">제휴/할인</a></li>\r\n");
      out.write("                                          <li><a style=\"color: white;\" href=\"about.html\">당첨자 발표</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                                  <li class=\"active\"><a id=\"mypage\" style=\"color: white;\" href=\"/orm/MyPage.jsp\">마이페이지</a></li>\r\n");
      out.write("                              </ul>\r\n");
      out.write("             \r\n");
      out.write("                              <!-- Newsletter Form -->\r\n");
      out.write("                          <!--     <div class=\"search-btn\">\r\n");
      out.write("                                  <i class=\"fa fa-search\" aria-hidden=\"true\"></i>\r\n");
      out.write("                              </div> -->\r\n");
      out.write("                          <!-- <div class=\"link-area\">\r\n");
      out.write("                           <a href=\"#\" class=\"header-icon-join\" title=\"마이 페이지\" style=\"margin-right: 10px;\">마이페이지</a>\r\n");
      out.write("                           <a href=\"#\" class=\"header-icon-ticket\" title=\"상영시간표\">상영시간표</a>\r\n");
      out.write("                          </div> -->\r\n");
      out.write("\r\n");
      out.write("                          </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Nav End -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div width: 100%; height: 600px\" id=\"homeBody\">\r\n");
      out.write("    <body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write(" <p style=\"color: white; font-size: 30px; font-weight: bold;\" >마이페이지</p>\r\n");
      out.write("  <table>\r\n");
      out.write("  \t<thead>\r\n");
      out.write("  \t\t<b style=\"font-size: 20px\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님</b>  \r\n");
      out.write("  \t\t\r\n");
      out.write("  \t</thead>\r\n");
      out.write("  </table>\r\n");
      out.write(" <ul class=\"nav nav-tabs\" style=\"margin-top: 20px;\">\r\n");
      out.write("    <li><a data-toggle=\"tab\" href=\"#menu1\">내정보</a></li>\r\n");
      out.write("    <li><a data-toggle=\"tab\" href=\"#menu2\">예매내역</a></li>\r\n");
      out.write("    <li><a data-toggle=\"tab\" href=\"#menu3\">내 리뷰</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"tab-content\">\r\n");
      out.write("    <div id=\"menu1\" class=\"tab-pane fade\" >\r\n");
      out.write("       <table>\r\n");
      out.write("      \t<tbody id=\"myPage\"><br><br><br>\r\n");
      out.write("      \t\r\n");
      out.write("      \t</tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"menu2\" class=\"tab-pane fade\">\r\n");
      out.write("      <div id=\"container\">\r\n");
      out.write("\t\t\t<div id=\"contentsWrap\" class=\"contentsWrap\">\r\n");
      out.write("\t\t\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t\t\t<form action=\"\" method=\"post\" name=\"searchFrm\">\r\n");
      out.write("\t\t\t\t\t<table class=\"bbsWrite mgb35\">\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: right;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>검색날짜<input type=\"date\">~<input type=\"date\"></span><button id=\"serach\">조회</button>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<table class=\"bbsList\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t <tr>\r\n");
      out.write("\t\t                     \r\n");
      out.write("\t\t                     <th scope=\"col\">예매번호</th>\r\n");
      out.write("\t\t                     <th scope=\"col\">예매날짜</th>\r\n");
      out.write("\t\t                     <th scope=\"col\">영화제목</th>\r\n");
      out.write("\t\t                     <th scope=\"col\">영화관</th>\r\n");
      out.write("\t\t                     <th scope=\"col\">상영관</th>\r\n");
      out.write("\t\t                     <th scope=\"col\">영화시간</th>\r\n");
      out.write("\t\t                     <th scope=\"col\">좌석</th>\r\n");
      out.write("\t\t                     <th scope=\"col\">좌석수</th>\r\n");
      out.write("\t\t                     <th scope=\"col\">가격</th>\r\n");
      out.write("\t\t                  </tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\t\r\n");
      out.write("\t\t\t\t\t\t<tbody id=\"seat\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"paging\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"/orm/img/button/btn_first.gif\" alt=\"처음페이지\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"/orm/img/button/btn_prev.gif\" alt=\"이전\"></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">1</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"/orm/img/button/btn_next.gif\" alt=\"다음\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"/orm/img/button/btn_last.gif\" alt=\"마지막페이지\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</span>\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"menu3\" class=\"tab-pane fade\">\r\n");
      out.write("      <div id=\"container\">\r\n");
      out.write("\t\t\t<div id=\"contentsWrap\" class=\"contentsWrap\">\r\n");
      out.write("\t\t\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t\t\t<table class=\"bbsList\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"150\" />\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>영화제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>영화감상평</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>평점</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>날짜</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\t\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"paging\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"/orm/img/button/btn_first.gif\" alt=\"처음페이지\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"/orm/img/button/btn_prev.gif\" alt=\"이전\"/></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">1</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"/orm/img/button/btn_next.gif\" alt=\"다음\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"/orm/img/button/btn_last.gif\" alt=\"마지막페이지\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</span>\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Footer Area Start ##### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### All Javascript Files ##### -->\r\n");
      out.write("    <!-- jQuery-2.2.4 js -->\r\n");
      out.write("    <script src=\"js/jquery/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("    <!-- Popper js -->\r\n");
      out.write("    <script src=\"js/bootstrap/popper.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap js -->\r\n");
      out.write("    <script src=\"js/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- All Plugins js -->\r\n");
      out.write("    <script src=\"js/plugins/plugins.js\"></script>\r\n");
      out.write("    <!-- Active js -->\r\n");
      out.write("    <script src=\"js/active.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /MyPage.jsp(127,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /MyPage.jsp(127,8) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SeatList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /MyPage.jsp(127,8) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("cnt");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.booking_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.movie_regdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.movie_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.movie_loc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.movie_screen}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.movie_time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.seat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.booking_amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.booking_charge}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("원</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><a href=\"SeatDelete.do?booking_no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.booking_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><button>예매취소</button></a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /MyPage.jsp(418,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("s");
      // /MyPage.jsp(418,7) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ReviewList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /MyPage.jsp(418,7) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("cnt");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt.count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.movie_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.con}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.rating}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.regdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
