/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-08-01 20:33:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class uploadMovie_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"/orm/images/icons/favicon.ico\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/orm/vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/orm/fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/orm/fonts/Linearicons-Free-v1.0.0/icon-font.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/orm/vendor/animate/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/orm/vendor/css-hamburgers/hamburgers.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/orm/vendor/animsition/css/animsition.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/orm/vendor/select2/select2.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/orm/vendor/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/orm/css/util.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/orm/css/main.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.0.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t//영화 업로드 제약사항\r\n");
      out.write("\t$(\"#submit\").click(function(){\r\n");
      out.write("\t\tif($(\"input#movie_title\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"영화제목을 입력하세요\");\r\n");
      out.write("\t\t\t$(\"input#movie_title\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif($(\"input#opendate\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"영화개봉일을 입력하세요\");\r\n");
      out.write("\t\t\t$(\"input#opendate\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"input#runningtime\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"상영시간을 입력하세요\");\r\n");
      out.write("\t\t\t$(\"input#runningtime\").focus();\r\n");
      out.write("\t\t\treturn ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"input#trailer\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"트레일러를 입력하세요\");\r\n");
      out.write("\t\t\t$(\"input#trailer\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"input#story\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"줄거리 입력하세요\");\r\n");
      out.write("\t\t\t$(\"input#story\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"input#director\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"감독을 입력하세요\");\r\n");
      out.write("\t\t\t$(\"input#director\").focus();\r\n");
      out.write("\t\t\treturn ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"input#actor\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"츌연자를 입력하세요\");\r\n");
      out.write("\t\t\t$(\"input#actor\").focus();\r\n");
      out.write("\t\t\treturn ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"form\").submit();\r\n");
      out.write("\t}); \r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\t\t\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"limiter\">\r\n");
      out.write("      <div class=\"container-login100\">\r\n");
      out.write("         <div class=\"wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55\">\r\n");
      out.write("            <!-- <form class=\"login100-form validate-form flex-sb flex-w\" action=\"/orm/uploadMovie.do\" method=\"post\"> -->\r\n");
      out.write("            <form id=\"uploadMovie\" name=\"uploadMovie\" method=\"post\" action=\"/orm/uploadMovie.do\">\r\n");
      out.write("               <span class=\"login100-form-title p-b-32\">\r\n");
      out.write("                  UPLOAD MOVIE\r\n");
      out.write("               </span>\r\n");
      out.write("<br>\r\n");
      out.write("               <span class=\"txt1 p-b-11\">\r\n");
      out.write("                  \t영화제목\r\n");
      out.write("               </span>\r\n");
      out.write("               <div class=\"wrap-input100 validate-input m-b-36\" data-validate = \"Username is required\">\r\n");
      out.write("                  <input class=\"input100\" type=\"text\" name=\"movie_title\" id=\"movie_title\">\r\n");
      out.write("                  <span class=\"focus-input100\"></span>\r\n");
      out.write("               </div>\r\n");
      out.write("               <span class=\"txt1 p-b-11\">\r\n");
      out.write("                 \t 장르\r\n");
      out.write("               </span>\r\n");
      out.write("               <div class=\"wrap-input100 validate-input m-b-36\" data-validate = \"Username is required\">\r\n");
      out.write("                  <input class=\"input100\" type=\"text\" name=\"genre\" id=\"genre\" >\r\n");
      out.write("                  <span class=\"focus-input100\"></span>\r\n");
      out.write("               </div>\r\n");
      out.write("               <span class=\"txt1 p-b-11\">\r\n");
      out.write("                 \t 개봉일\r\n");
      out.write("               </span>\r\n");
      out.write("               <div class=\"wrap-input100 validate-input m-b-36\" data-validate = \"Username is required\">\r\n");
      out.write("                  <input class=\"input100\" type=\"text\" name=\"opendate\" id=\"opendate\"  placeholder=\"2019.04.24\">\r\n");
      out.write("                  <span class=\"focus-input100\"></span>\r\n");
      out.write("               </div>\r\n");
      out.write("               <span class=\"txt1 p-b-11\">\r\n");
      out.write("                \t  상영시간\r\n");
      out.write("               </span>\r\n");
      out.write("               <div class=\"wrap-input100 validate-input m-b-36\" data-validate = \"Username is required\">\r\n");
      out.write("                  <input class=\"input100\" type=\"text\" name=\"runningtime\" id=\"runningtime\" >\r\n");
      out.write("                  <span class=\"focus-input100\"></span>\r\n");
      out.write("               </div>\r\n");
      out.write("               <span class=\"txt1 p-b-11\">\r\n");
      out.write("                  \t트레일러\r\n");
      out.write("               </span>\r\n");
      out.write("               <div class=\"wrap-input100 validate-input m-b-36\"  data-validate = \"Username is required\">\r\n");
      out.write("                  <input class=\"input100\" type=\"text\" name=\"trailer\" id=\"trailer\" >\r\n");
      out.write("                  <span class=\"focus-input100\"></span>\r\n");
      out.write("               </div>\r\n");
      out.write("               <span class=\"txt1 p-b-11\">\r\n");
      out.write("                 \t 스토리\r\n");
      out.write("               </span>\r\n");
      out.write("                <div class=\"wrap-input100 validate-input m-b-36\"  data-validate = \"Username is required\">\r\n");
      out.write("                  <input class=\"input100\" type=\"text\" name=\"story\" id=\"story\" >\r\n");
      out.write("                  <span class=\"focus-input100\"></span>\r\n");
      out.write("               </div>\r\n");
      out.write("               <span class=\"txt1 p-b-11\">\r\n");
      out.write("                  \t감독\r\n");
      out.write("               </span>\r\n");
      out.write("                <div class=\"wrap-input100 validate-input m-b-36\"  data-validate = \"Username is required\">\r\n");
      out.write("                  <input class=\"input100\" type=\"text\" name=\"director\" id=\"director\" >\r\n");
      out.write("                  <span class=\"focus-input100\"></span>\r\n");
      out.write("               </div>\r\n");
      out.write("               <span class=\"txt1 p-b-11\">\r\n");
      out.write("                  \t출연\r\n");
      out.write("               </span>\r\n");
      out.write("               <div class=\"wrap-input100 validate-input m-b-36\"  data-validate = \"Username is required\">\r\n");
      out.write("                  <input class=\"input100\" type=\"text\" name=\"actor\" id=\"actor\" >\r\n");
      out.write("                  <span class=\"focus-input100\"></span>\r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("               <div class=\"container-login100-form-btn\">\r\n");
      out.write("                  <button class=\"login100-form-btn\" id=\"submit\" name=\"submit\">\r\n");
      out.write("                     \t등록\r\n");
      out.write("                  </button>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   <div id=\"dropDownSelect1\"></div>\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
