/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-08-07 08:11:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages_005fcss;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tfont-size: 28px;\r\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("\tbackground-color: #f1f1f1;\r\n");
      out.write("    padding-top: 50px;\r\n");
      out.write("    padding-bottom: 8px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write(" /* header - 맨위  */\r\n");
      out.write(" .header  div {\r\n");
      out.write(" \ttext-align: right;\r\n");
      out.write(" \tmargin-bottom: 0;\r\n");
      out.write(" \r\n");
      out.write(" }\r\n");
      out.write(" .header  div a{\r\n");
      out.write(" \tfont-size: 15px;\r\n");
      out.write("    padding-left: 30px;\r\n");
      out.write(" }\r\n");
      out.write(" /* header - 맨위  */\r\n");
      out.write("\r\n");
      out.write("#navbar {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, .3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar a {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tcolor: #f2f2f2;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 14px 85px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar a:hover {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar a.active {\r\n");
      out.write("\tbackground-color: #4CAF50;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("\tpadding: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sticky {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sticky+.content {\r\n");
      out.write("\tpadding-top: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar .search-container {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar input[type=text] {\r\n");
      out.write("\tpadding: 6px;\r\n");
      out.write("\tmargin-top: 8px;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar .search-container button {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tpadding: 6px 10px;\r\n");
      out.write("\tmargin-top: 8px;\r\n");
      out.write("\tmargin-right: 16px;\r\n");
      out.write("\tbackground: #ddd;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar .search-container button:hover {\r\n");
      out.write("\tbackground: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 600px) {\r\n");
      out.write("\t#navbar .search-container {\r\n");
      out.write("\t\tfloat: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t#navbar a, .topnav input[type=text], #navbar .search-container button {\r\n");
      out.write("\t\tfloat: none;\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 14px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#navbar input[type=text] {\r\n");
      out.write("\t\tborder: 1px solid #ccc;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown .dropbtn {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 14px 16px;\r\n");
      out.write("\tbackground-color: inherit;\r\n");
      out.write("\tfont-family: inherit;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tbackground-color: #f9f9f9;\r\n");
      out.write("\tmin-width: 160px;\r\n");
      out.write("\tbox-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a {\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tpadding: 12px 16px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a:hover {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown:hover .dropdown-content {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write(" <script>\r\n");
      out.write("       $(function(){\r\n");
      out.write("          $(\"a#signup\").click(function(){\r\n");
      out.write("             //window.open(\"/orm/jsp/signup.jsp\",'left=300,top=100,width=400,height=300')\r\n");
      out.write("             document.location.href='/orm/jsp/signup.jsp';\r\n");
      out.write("          });\r\n");
      out.write("          $(\"a#signin\").click(function(){\r\n");
      out.write("             //window.open(\"/orm/jsp/signin.jsp\",'left=300,top=100,width=400,height=300')\r\n");
      out.write("             document.location.href='/orm/jsp/signin.jsp';\r\n");
      out.write("          });\r\n");
      out.write("          $(\"#btnSearch\").click(function(){\r\n");
      out.write("             var searchData=$(\"input#movieSearch\").val();\r\n");
      out.write("             if(searchData.length==0){\r\n");
      out.write("               alert('영화명을 입력해 주세요');\r\n");
      out.write("               $(\"input#movieSearch\").val('');\r\n");
      out.write("               $(\"input#movieSearch\").focus();\r\n");
      out.write("             }else{\r\n");
      out.write("                alert(searchData);\r\n");
      out.write("                $(\"form#searchFrm\").submit();\r\n");
      out.write("             }\r\n");
      out.write("            \r\n");
      out.write("          });\r\n");
      out.write("\r\n");
      out.write("          if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"!=null && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length>0){\r\n");
      out.write("             if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length>0 && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"!='admin'){\r\n");
      out.write("            $(\"a#mypage\").show();\r\n");
      out.write("            $(\"a#logOut\").show();\r\n");
      out.write("            $(\"a#sign\").hide();\r\n");
      out.write("            $(\"a#signup\").hide();\r\n");
      out.write("            $(\"a#signup\").hide();\r\n");
      out.write("            $(\"a#adminpage\").hide();}\r\n");
      out.write("             if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".length>0 && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"=='admin'){ \r\n");
      out.write("                $(\"a#mypage\").hide();\r\n");
      out.write("                $(\"a#logOut\").show();\r\n");
      out.write("                $(\"a#sign\").hide();\r\n");
      out.write("                $(\"a#signup\").hide();\r\n");
      out.write("                $(\"a#signup\").hide();\r\n");
      out.write("                $(\"a#adminpage\").show();}\r\n");
      out.write("             }\r\n");
      out.write("            else{\r\n");
      out.write("               $(\"a#adminpage\").hide();\r\n");
      out.write("               $(\"a#mypage\").hide();\r\n");
      out.write("               $(\"a#logOut\").hide();\r\n");
      out.write("               $(\"a#sign\").show();\r\n");
      out.write("            \r\n");
      out.write("            }  \r\n");
      out.write(" \t\t});           \r\n");
      out.write("           \r\n");
      out.write("  \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header >\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"signup.do\" id=\"signup\">회원가입</a>\r\n");
      out.write("\t\t\t\t<!--로그인시 hidden 처리되게  -->\r\n");
      out.write("\t\t\t\t<a href=\"signin.do\" id=\"sign\">로그인</a>\r\n");
      out.write("\t\t\t\t<!--로그인시 '로그아웃'으로 바뀌게 하기  -->\r\n");
      out.write("\t\t\t\t<a href=\"logOut.do\" id=\"logOut\">로그아웃</a>\r\n");
      out.write("\t\t\t\t<!--로그인시 '로그아웃'으로 바뀌게 하기  -->\r\n");
      out.write("\t\t\t\t<a href=\"boardList.do\">고객센터</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div >\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div id=\"navbar\">\r\n");
      out.write("\t\t\t\t\t<a id=\"navbar-contents\" class=\"active\" href=\"/orm/index2.jsp\">Home</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"dropbtn\">\r\n");
      out.write("\t\t\t\t\t\t\t영화 <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">전체영화</a> <a href=\"#\">무비파인더</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a id=\"navbar-contents\" href=\"javascript:void(0)\">예매</a> <a\r\n");
      out.write("\t\t\t\t\t\tid=\"navbar-contents\" href=\"javascript:void(0)\">극장</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"search-container\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"/action_page.php\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Search..\" name=\"search\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\twindow.onscroll = function() {\r\n");
      out.write("\t\t\tmyFunction()\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tvar navbar = document.getElementById(\"navbar\");\r\n");
      out.write("\t\tvar sticky = navbar.offsetTop;\r\n");
      out.write("\r\n");
      out.write("\t\tfunction myFunction() {\r\n");
      out.write("\t\t\tif (window.pageYOffset >= sticky) {\r\n");
      out.write("\t\t\t\tnavbar.classList.add(\"sticky\")\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tnavbar.classList.remove(\"sticky\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
